## Configuration file for DWGettingStarted application.
---
# User login.
login: javaeeeee
# User  password.
password: crimson

#Server configuration.
server:
    applicationConnectors:
        - type: http
          port: 8081
        - type: https
          port: 8444
          keyStorePath: dwstart.keystore
          keyStorePassword: crimson
          validateCerts: false